# Generated by Django 4.2.6 on 2023-12-18 16:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='')),
                ('image2', models.ImageField(null=True, upload_to='')),
                ('image3', models.ImageField(null=True, upload_to='')),
                ('image4', models.ImageField(null=True, upload_to='')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('about_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='add_guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=50, unique=True)),
                ('guide_age', models.IntegerField(unique=True)),
                ('guide_contact_number', models.CharField(max_length=100)),
                ('guide_aadhar_number', models.CharField(max_length=100, unique=True)),
                ('guide_experience', models.FloatField()),
                ('guide_aadhar', models.ImageField(upload_to='')),
                ('guide_tem_add', models.TextField()),
                ('guide_permanent_add', models.TextField()),
                ('guide_languages_known', models.CharField(max_length=100)),
                ('gender', models.CharField(default=False, max_length=10)),
                ('guide_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('guide_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='add_hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=20)),
                ('type_of_hotel', models.CharField(max_length=20)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('total_rooms', models.IntegerField()),
                ('type_of_rooms', models.CharField(max_length=10)),
                ('location', models.URLField()),
                ('Address', models.TextField(blank=True)),
                ('hotel_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('hotel_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='add_vehicle_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=100, null=True, unique=True)),
                ('seating_capacity', models.IntegerField()),
                ('vehicle_details_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type_of_transport', models.CharField(max_length=20)),
                ('vehicle_details_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='add_vehicle_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vehicle', models.CharField(max_length=100)),
                ('mode_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mode_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='add_vehicle_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_vehicle', models.CharField(max_length=100)),
                ('mode_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mode_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_image', models.ImageField(upload_to='')),
                ('city_name', models.CharField(max_length=20, unique=True)),
                ('city_description', models.TextField()),
                ('city_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('city_status', models.BooleanField(default=False)),
                ('city_short_code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='')),
                ('subject', models.TextField()),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('mobile_num', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contact_status', models.BooleanField(default=False)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_image', models.ImageField(upload_to='')),
                ('country_name', models.CharField(max_length=20, unique=True)),
                ('country_short_code', models.CharField(max_length=8, unique=True)),
                ('country_description', models.TextField()),
                ('country_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('country_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='package_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=100, null=True, unique=True)),
                ('package_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('package_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_image', models.ImageField(upload_to='')),
                ('state_name', models.CharField(max_length=20, unique=True)),
                ('state_short_code', models.CharField(max_length=8, unique=True)),
                ('state_description', models.TextField()),
                ('state_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('state_status', models.BooleanField(default=False)),
                ('state_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.country')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('users_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tourplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_image', models.ImageField(upload_to='')),
                ('tour_name', models.CharField(max_length=20, unique=True)),
                ('tour_description', models.TextField(blank=True, null=True)),
                ('tour_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tour_status', models.BooleanField(default=False)),
                ('tour_short_code', models.CharField(max_length=8)),
                ('tour_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.city')),
                ('tour_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.country')),
                ('tour_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.state')),
            ],
        ),
        migrations.CreateModel(
            name='tour_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourimage1', models.ImageField(upload_to='')),
                ('tourimage2', models.ImageField(upload_to='')),
                ('tourimage3', models.ImageField(upload_to='')),
                ('open_time', models.CharField(max_length=20)),
                ('closed_time', models.CharField(max_length=20)),
                ('tourdescription', models.TextField(blank=True, null=True)),
                ('tourcreated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('tourstatus', models.BooleanField(default=False)),
                ('tourshort_code', models.CharField(max_length=8)),
                ('hotel_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.add_hotel')),
                ('tourcity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.city')),
                ('tourcountry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.country')),
                ('tourname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.tourplace')),
                ('tourstate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.state')),
                ('type_of_vehicle', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.add_vehicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='package_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_persons', models.IntegerField(blank=True)),
                ('package_code', models.CharField(max_length=10, unique=True)),
                ('duration', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('package_details_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('package_details_status', models.BooleanField(default=False)),
                ('iternary', models.TextField()),
                ('city_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.city')),
                ('country_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.country')),
                ('guide_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.add_guide')),
                ('hotel_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.add_hotel')),
                ('package_type', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.package_type')),
                ('state_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.state')),
                ('tour_places', models.ManyToManyField(to='admin_pannel.tourplace')),
                ('type_of_vehicle', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.add_vehicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='manage_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('contact', models.BigIntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default=False, max_length=10)),
                ('profile', models.ImageField(max_length=12, unique=True, upload_to='')),
                ('users_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_status', models.BooleanField(default=False)),
                ('package_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.package_details')),
            ],
        ),
        migrations.CreateModel(
            name='iterinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iternary_status', models.BooleanField(default=False)),
                ('iterinary_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mode_of_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.add_vehicle_details')),
                ('package_tour_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.package_details')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='city_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.state'),
        ),
        migrations.AddField(
            model_name='add_vehicle_details',
            name='name_of_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.add_vehicle_name'),
        ),
        migrations.AddField(
            model_name='add_vehicle_details',
            name='type_of_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.add_vehicle_type'),
        ),
        migrations.AddField(
            model_name='add_hotel',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.city'),
        ),
        migrations.AddField(
            model_name='add_hotel',
            name='country_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.country'),
        ),
        migrations.AddField(
            model_name='add_hotel',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.package_type'),
        ),
        migrations.AddField(
            model_name='add_hotel',
            name='state_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.state'),
        ),
    ]
