# Generated by Django 4.2.6 on 2023-12-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('subject', models.CharField(default=True, max_length=50, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('fullname', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('confirm_password', models.CharField(max_length=80)),
                ('otp', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='user_pannel.register')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.PositiveIntegerField(null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.BooleanField()),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='user_pannel.register')),
            ],
        ),
    ]
