# Generated by Django 4.2.6 on 2024-01-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_pannel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='registration_id',
        ),
    ]
